import type { Member, Coach, Play, Touch } from "./types";

export const DUMMY_COACHES: Coach[] = [
  { id: "c1", name: "Alex Rivera" },
  { id: "c2", name: "Jordan Lee" },
  { id: "c3", name: "Sam Chen" },
  { id: "c4", name: "Morgan Taylor" },
];

export const DUMMY_PLAYS: Play[] = [
  {
    id: "p1",
    name: "21-day check-in",
    whenToUse: "No visit in 14–21 days",
    timeToRun: "~5 min",
    steps: ["Send SMS", "Log response", "Book if needed"],
    lifecycleStage: "At Risk",
    goal: "Re-engage",
    channel: "SMS",
  },
  {
    id: "p2",
    name: "We miss you call",
    whenToUse: "High risk, no touch in 7 days",
    timeToRun: "~10 min",
    steps: ["Call member", "Note outcome", "Schedule follow-up"],
    lifecycleStage: "At Risk",
    goal: "Re-engage",
    channel: "Call",
  },
  {
    id: "p3",
    name: "Plateau nudge",
    whenToUse: "Attendance flat 4+ weeks",
    timeToRun: "~3 min",
    steps: ["Send email", "Suggest class", "Log touch"],
    lifecycleStage: "Slipping",
    goal: "Activate",
    channel: "Email",
  },
  {
    id: "p4",
    name: "Win-back offer",
    whenToUse: "Cancelled, within 60 days",
    timeToRun: "~5 min",
    steps: ["Send offer", "Track reply", "Convert or close"],
    lifecycleStage: "Win-back",
    goal: "Win-back",
    channel: "Email",
  },
  {
    id: "p5",
    name: "Payment check",
    whenToUse: "Payment friction flag",
    timeToRun: "~5 min",
    steps: ["Review plan", "Call or email", "Resolve or pause"],
    lifecycleStage: "At Risk",
    goal: "Retain",
    channel: "Call",
  },
  {
    id: "p6",
    name: "Quick DM",
    whenToUse: "Light touch, social member",
    timeToRun: "~2 min",
    steps: ["DM", "Log outcome"],
    lifecycleStage: "Slipping",
    goal: "Re-engage",
    channel: "DM",
  },
  {
    id: "p7",
    name: "In-person catch-up",
    whenToUse: "Member in gym, at risk",
    timeToRun: "~15 min",
    steps: ["Greet", "Chat", "Log touch"],
    lifecycleStage: "At Risk",
    goal: "Re-engage",
    channel: "In person",
  },
  {
    id: "p8",
    name: "Overdue touch reminder",
    whenToUse: "No touch in 10+ days",
    timeToRun: "~5 min",
    steps: ["Pick channel", "Reach out", "Log touch"],
    lifecycleStage: "At Risk",
    goal: "Re-engage",
    channel: "SMS",
  },
];

const twoDaysAgo = new Date();
twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);
const fiveDaysAgo = new Date();
fiveDaysAgo.setDate(fiveDaysAgo.getDate() - 5);
const eightDaysAgo = new Date();
eightDaysAgo.setDate(eightDaysAgo.getDate() - 8);
const twelveDaysAgo = new Date();
twelveDaysAgo.setDate(twelveDaysAgo.getDate() - 12);

export const DUMMY_MEMBERS: Member[] = [
  {
    id: "m1",
    name: "Jamie Walsh",
    plan: "Premium",
    mrr: 65,
    status: "at_risk",
    healthScore: 32,
    habitDecay: 3,
    reasons: ["Attendance drop", "No bookings"],
    ownerCoachId: "c1",
    lastTouchAt: twoDaysAgo.toISOString(),
    nextSessionAt: null,
  },
  {
    id: "m2",
    name: "Sam Kelly",
    plan: "Standard",
    mrr: 45,
    status: "at_risk",
    healthScore: 28,
    habitDecay: 3,
    reasons: ["No bookings"],
    ownerCoachId: "c1",
    lastTouchAt: fiveDaysAgo.toISOString(),
    nextSessionAt: null,
  },
  {
    id: "m3",
    name: "Riley Jones",
    plan: "Premium",
    mrr: 65,
    status: "slipping",
    healthScore: 48,
    habitDecay: 2,
    reasons: ["Plateau"],
    ownerCoachId: "c2",
    lastTouchAt: twoDaysAgo.toISOString(),
    nextSessionAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "m4",
    name: "Morgan Blake",
    plan: "Basic",
    mrr: 35,
    status: "at_risk",
    healthScore: 22,
    habitDecay: 3,
    reasons: ["Attendance drop", "Payment friction"],
    ownerCoachId: "c2",
    lastTouchAt: twelveDaysAgo.toISOString(),
    nextSessionAt: null,
  },
  {
    id: "m5",
    name: "Casey Drew",
    plan: "Standard",
    mrr: 45,
    status: "win_back",
    healthScore: 18,
    habitDecay: 3,
    reasons: ["No bookings"],
    ownerCoachId: "c3",
    lastTouchAt: eightDaysAgo.toISOString(),
    nextSessionAt: null,
  },
  {
    id: "m6",
    name: "Jordan Avery",
    plan: "Premium",
    mrr: 65,
    status: "slipping",
    healthScore: 52,
    habitDecay: 1,
    reasons: ["Plateau"],
    ownerCoachId: "c3",
    lastTouchAt: twoDaysAgo.toISOString(),
    nextSessionAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "m7",
    name: "Alex Quinn",
    plan: "Standard",
    mrr: 45,
    status: "at_risk",
    healthScore: 38,
    habitDecay: 2,
    reasons: ["Attendance drop"],
    ownerCoachId: "c4",
    lastTouchAt: fiveDaysAgo.toISOString(),
    nextSessionAt: null,
  },
  {
    id: "m8",
    name: "Taylor Reed",
    plan: "Basic",
    mrr: 35,
    status: "at_risk",
    healthScore: 25,
    habitDecay: 3,
    reasons: ["No bookings", "Payment friction"],
    ownerCoachId: "c1",
    lastTouchAt: null,
    nextSessionAt: null,
  },
  {
    id: "m9",
    name: "Skyler Gray",
    plan: "Premium",
    mrr: 65,
    status: "slipping",
    healthScore: 55,
    habitDecay: 1,
    reasons: [],
    ownerCoachId: "c2",
    lastTouchAt: twoDaysAgo.toISOString(),
    nextSessionAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "m10",
    name: "Parker Lane",
    plan: "Standard",
    mrr: 45,
    status: "win_back",
    healthScore: 15,
    habitDecay: 3,
    reasons: ["Attendance drop"],
    ownerCoachId: "c4",
    lastTouchAt: eightDaysAgo.toISOString(),
    nextSessionAt: null,
  },
  {
    id: "m11",
    name: "Drew Morgan",
    plan: "Basic",
    mrr: 35,
    status: "at_risk",
    healthScore: 30,
    habitDecay: 2,
    reasons: ["No bookings"],
    ownerCoachId: "",
    lastTouchAt: twelveDaysAgo.toISOString(),
    nextSessionAt: null,
  },
  {
    id: "m12",
    name: "Blake Riley",
    plan: "Standard",
    mrr: 45,
    status: "at_risk",
    healthScore: 42,
    habitDecay: 2,
    reasons: ["Plateau"],
    ownerCoachId: "c3",
    lastTouchAt: null,
    nextSessionAt: null,
  },
];

const t1 = new Date();
t1.setHours(t1.getHours() - 2);
const t2 = new Date();
t2.setDate(t2.getDate() - 1);
const t3 = new Date();
t3.setDate(t3.getDate() - 3);

export const DUMMY_TOUCHES: Touch[] = [
  {
    id: "t1",
    memberId: "m1",
    coachId: "c1",
    createdAt: t1.toISOString(),
    channel: "sms",
    type: "coach",
    outcome: "replied",
    notes: "Said will book this week",
  },
  {
    id: "t2",
    memberId: "m1",
    coachId: "c1",
    createdAt: t2.toISOString(),
    channel: "call",
    type: "coach",
    outcome: "booked",
    notes: "Booked for Thu",
  },
  {
    id: "t3",
    memberId: "m3",
    coachId: "c2",
    createdAt: t3.toISOString(),
    channel: "play_launch",
    type: "system",
    playId: "p3",
    outcome: "replied",
  },
  {
    id: "t4",
    memberId: "m4",
    coachId: "c2",
    createdAt: eightDaysAgo.toISOString(),
    channel: "email",
    type: "coach",
    outcome: "no_response",
    notes: "Sent offer",
  },
  {
    id: "t5",
    memberId: "m6",
    coachId: "c3",
    createdAt: twoDaysAgo.toISOString(),
    channel: "in_person",
    type: "coach",
    outcome: "replied",
    notes: "Chat at reception",
  },
];
