/**
 * Mock data for mission-control Coach Accountability page
 * Client-side only – no backend
 */

import type {
  Member,
  Coach,
  Interaction,
  RetentionPlay,
  Task,
  CoachMetrics,
  TeamMetrics,
  AutomationRule,
} from "./mission-control-types";

const now = new Date();
const d = (daysAgo: number) => {
  const x = new Date(now);
  x.setDate(x.getDate() - daysAgo);
  return x.toISOString();
};
const genSeries = (len: number, base: number, decay: boolean) =>
  Array.from({ length: len }, (_, i) => ({
    date: d(len - 1 - i),
    value: Math.max(0, base + (decay ? -i * 3 : i) + Math.random() * 5),
  }));

export const MOCK_COACHES: Coach[] = [
  { id: "c1", name: "Alex Rivera", role: "Head Coach" },
  { id: "c2", name: "Jordan Lee", role: "Coach" },
  { id: "c3", name: "Sam Chen", role: "Coach" },
  { id: "c4", name: "Morgan Taylor", role: "Coach" },
];

export const MOCK_MEMBERS: Member[] = [
  {
    id: "m1",
    name: "Jamie Walsh",
    saved: true,
    membershipType: "Premium",
    joinDate: d(120),
    coachOwnerId: "c1",
    riskLevel: "high",
    churnProbability: 78,
    commitmentScore: 32,
    habitDecayVelocity: 2.4,
    lifecycleStage: "at_risk_silent_quit",
    riskReasons: ["Attendance drop 40%", "Missed 3 sessions"],
    lastVisitDate: d(9),
    lastInteractionDate: d(2),
    attendanceSeries: genSeries(14, 60, true),
    commitmentSeries: genSeries(14, 55, true),
    socialSeries: genSeries(14, 20, true),
    touchSeries: genSeries(14, 5, false),
    tags: ["schedule stress"],
  },
  {
    id: "m2",
    name: "Sam Kelly",
    membershipType: "Standard",
    joinDate: d(90),
    coachOwnerId: "c1",
    riskLevel: "high",
    churnProbability: 82,
    commitmentScore: 28,
    habitDecayVelocity: 2.8,
    lifecycleStage: "at_risk_silent_quit",
    riskReasons: ["No bookings", "Missed 4 sessions"],
    lastVisitDate: d(14),
    lastInteractionDate: d(5),
    attendanceSeries: genSeries(14, 70, true),
    commitmentSeries: genSeries(14, 50, true),
    socialSeries: genSeries(14, 15, true),
    touchSeries: genSeries(14, 3, false),
    tags: ["motivation drop"],
  },
  {
    id: "m3",
    name: "Riley Jones",
    saved: true,
    membershipType: "Premium",
    joinDate: d(200),
    coachOwnerId: "c2",
    riskLevel: "moderate",
    churnProbability: 45,
    commitmentScore: 48,
    habitDecayVelocity: 1.2,
    lifecycleStage: "plateau_boredom_risk",
    riskReasons: ["Attendance plateau 4 weeks"],
    lastVisitDate: d(3),
    lastInteractionDate: d(2),
    attendanceSeries: genSeries(14, 55, false),
    commitmentSeries: genSeries(14, 50, false),
    socialSeries: genSeries(14, 30, false),
    touchSeries: genSeries(14, 8, false),
    tags: [],
  },
  {
    id: "m4",
    name: "Morgan Blake",
    membershipType: "Basic",
    joinDate: d(60),
    coachOwnerId: "c2",
    riskLevel: "high",
    churnProbability: 88,
    commitmentScore: 22,
    habitDecayVelocity: 3.1,
    lifecycleStage: "at_risk_silent_quit",
    riskReasons: ["Attendance drop", "Payment friction"],
    lastVisitDate: d(12),
    lastInteractionDate: d(8),
    attendanceSeries: genSeries(14, 40, true),
    commitmentSeries: genSeries(14, 35, true),
    socialSeries: genSeries(14, 10, true),
    touchSeries: genSeries(14, 2, false),
    tags: ["injury"],
  },
  {
    id: "m5",
    name: "Casey Drew",
    membershipType: "Standard",
    joinDate: d(180),
    coachOwnerId: "c3",
    riskLevel: "high",
    churnProbability: 92,
    commitmentScore: 18,
    habitDecayVelocity: 3.5,
    lifecycleStage: "win_back_window",
    riskReasons: ["No bookings", "Cancelled classes"],
    lastVisitDate: d(21),
    lastInteractionDate: d(8),
    attendanceSeries: genSeries(14, 20, true),
    commitmentSeries: genSeries(14, 25, true),
    socialSeries: genSeries(14, 5, true),
    touchSeries: genSeries(14, 1, false),
    tags: [],
  },
  {
    id: "m6",
    name: "Jordan Avery",
    saved: true,
    membershipType: "Premium",
    joinDate: d(150),
    coachOwnerId: "c3",
    riskLevel: "low",
    churnProbability: 25,
    commitmentScore: 52,
    habitDecayVelocity: 0.5,
    lifecycleStage: "plateau_boredom_risk",
    riskReasons: ["Light plateau"],
    lastVisitDate: d(1),
    lastInteractionDate: d(2),
    attendanceSeries: genSeries(14, 65, false),
    commitmentSeries: genSeries(14, 55, false),
    socialSeries: genSeries(14, 40, false),
    touchSeries: genSeries(14, 10, false),
    tags: [],
  },
  {
    id: "m7",
    name: "Alex Quinn",
    membershipType: "Standard",
    joinDate: d(100),
    coachOwnerId: "c4",
    riskLevel: "moderate",
    churnProbability: 55,
    commitmentScore: 38,
    habitDecayVelocity: 1.8,
    lifecycleStage: "emotional_disengagement",
    riskReasons: ["Attendance drop 30%"],
    lastVisitDate: d(5),
    lastInteractionDate: d(5),
    attendanceSeries: genSeries(14, 50, true),
    commitmentSeries: genSeries(14, 45, true),
    socialSeries: genSeries(14, 25, true),
    touchSeries: genSeries(14, 6, false),
    tags: ["schedule stress"],
  },
  {
    id: "m8",
    name: "Taylor Reed",
    membershipType: "Basic",
    joinDate: d(45),
    coachOwnerId: "c1",
    riskLevel: "high",
    churnProbability: 75,
    commitmentScore: 25,
    habitDecayVelocity: 2.6,
    lifecycleStage: "at_risk_silent_quit",
    riskReasons: ["No bookings", "New member low attendance"],
    lastVisitDate: null,
    lastInteractionDate: null,
    attendanceSeries: genSeries(14, 30, true),
    commitmentSeries: genSeries(14, 40, true),
    socialSeries: genSeries(14, 10, true),
    touchSeries: genSeries(14, 0, false),
    tags: [],
  },
  {
    id: "m9",
    name: "Drew Morgan",
    membershipType: "Basic",
    joinDate: d(80),
    coachOwnerId: "", // Unassigned
    riskLevel: "high",
    churnProbability: 72,
    commitmentScore: 30,
    habitDecayVelocity: 2.2,
    lifecycleStage: "at_risk_silent_quit",
    riskReasons: ["No bookings"],
    lastVisitDate: d(12),
    lastInteractionDate: d(12),
    attendanceSeries: genSeries(14, 35, true),
    commitmentSeries: genSeries(14, 38, true),
    socialSeries: genSeries(14, 15, true),
    touchSeries: genSeries(14, 2, false),
    tags: [],
  },
];

export const MOCK_INTERACTIONS: Interaction[] = [
  {
    id: "i1",
    memberId: "m1",
    coachId: "c1",
    timestamp: d(0).replace("T00:00", "T10:30"),
    type: "sms",
    notes: "Said will book this week",
    outcome: "rebooked",
  },
  {
    id: "i2",
    memberId: "m1",
    coachId: "c1",
    timestamp: d(2),
    type: "call",
    playId: "p1",
    notes: "Booked for Thu",
    outcome: "attended_next",
    followUpDate: d(-1),
  },
  {
    id: "i3",
    memberId: "m3",
    coachId: "c2",
    timestamp: d(3),
    type: "email",
    playId: "p3",
    outcome: "rebooked",
  },
  {
    id: "i4",
    memberId: "m4",
    coachId: "c2",
    timestamp: d(8),
    type: "email",
    notes: "Sent offer",
    outcome: "no_response",
    followUpDate: d(2),
  },
  {
    id: "i5",
    memberId: "m6",
    coachId: "c3",
    timestamp: d(2),
    type: "in_person",
    notes: "Chat at reception",
    outcome: "rebooked",
  },
];

export const MOCK_PLAYS: RetentionPlay[] = [
  {
    id: "p1",
    name: "21-day check-in",
    category: "re_engage",
    stageTargets: ["at_risk_silent_quit", "win_back_window"],
    triggerReasons: ["Missed 2 sessions", "Attendance drop"],
    suggestedChannel: "sms",
    templateMessage: "Hi {{firstName}}, we miss you! Haven't seen you in a while. Want to book a session this week?",
    callScript: "Greet warmly. Ask how they're doing. Offer to book next session.",
    expectedOutcome: "Re-engage and book",
  },
  {
    id: "p2",
    name: "We miss you call",
    category: "re_engage",
    stageTargets: ["at_risk_silent_quit"],
    triggerReasons: ["High risk", "No touch in 7 days"],
    suggestedChannel: "call",
    templateMessage: "Personal call – we miss you",
    callScript: "1. Greet 2. Acknowledge absence 3. Ask what would help 4. Offer to book",
    expectedOutcome: "Book or schedule follow-up",
  },
  {
    id: "p3",
    name: "Plateau nudge",
    category: "micro_commitment",
    stageTargets: ["plateau_boredom_risk"],
    triggerReasons: ["Attendance plateau", "Missed 2 sessions"],
    suggestedChannel: "email",
    templateMessage: "Hi {{firstName}}, noticed your consistency lately. Ready for a new challenge? Try our [class] this week.",
    expectedOutcome: "Re-engage and vary routine",
  },
  {
    id: "p4",
    name: "Win-back offer",
    category: "re_engage",
    stageTargets: ["win_back_window"],
    triggerReasons: ["Cancelled", "Long gap"],
    suggestedChannel: "email",
    templateMessage: "We'd love to have you back. Here's a special offer for your next visit.",
    expectedOutcome: "Return visit",
  },
  {
    id: "p5",
    name: "Quick DM reconnection",
    category: "social_reconnect",
    stageTargets: ["emotional_disengagement", "plateau_boredom_risk"],
    triggerReasons: ["Social drop"],
    suggestedChannel: "whatsapp",
    templateMessage: "Hey! How's it going? We've got a great class tomorrow – join us?",
    expectedOutcome: "Social reconnection",
  },
];

export const MOCK_TASKS: Task[] = [
  { id: "t1", coachId: "c1", memberId: "m2", title: "Follow up - no response", dueDate: d(-1), status: "overdue", priority: 1 },
  { id: "t2", coachId: "c1", memberId: "m8", title: "Initial outreach", dueDate: d(0), status: "due", priority: 1 },
  { id: "t3", coachId: "c2", memberId: "m4", title: "Call after email", dueDate: d(2), status: "waiting", priority: 2 },
  { id: "t4", coachId: "c3", memberId: "m5", title: "Win-back call", dueDate: d(1), status: "todo", priority: 1 },
  { id: "t5", coachId: "c1", memberId: "m1", title: "Check-in post visit", dueDate: d(3), status: "todo", priority: 2 },
  { id: "t6", coachId: "c2", memberId: "m3", title: "Session booked - confirm", dueDate: d(2), status: "done", priority: 2 },
];

export const MOCK_COACH_METRICS: CoachMetrics[] = [
  {
    coachId: "c1",
    membersAssignedCount: 4,
    atRiskAssignedCount: 3,
    contactedTodayCount: 2,
    contactedThisWeekCount: 8,
    contactCoveragePct: 67,
    avgResponseTimeHours: 4.2,
    responseRatePct: 72,
    reengagementRatePct: 38,
    saveRatePct: 25,
    behaviourImprovementRatePct: 42,
    membersSavedThisMonth: 2,
    revenueRetainedThisMonthGBP: 130,
    coachRetentionScore: 78,
    outreachStreakDays: 7,
  },
  {
    coachId: "c2",
    membersAssignedCount: 3,
    atRiskAssignedCount: 2,
    contactedTodayCount: 1,
    contactedThisWeekCount: 6,
    contactCoveragePct: 75,
    avgResponseTimeHours: 5.1,
    responseRatePct: 68,
    reengagementRatePct: 35,
    saveRatePct: 20,
    behaviourImprovementRatePct: 40,
    membersSavedThisMonth: 1,
    revenueRetainedThisMonthGBP: 65,
    coachRetentionScore: 72,
    outreachStreakDays: 3,
  },
  {
    coachId: "c3",
    membersAssignedCount: 2,
    atRiskAssignedCount: 1,
    contactedTodayCount: 2,
    contactedThisWeekCount: 7,
    contactCoveragePct: 85,
    avgResponseTimeHours: 3.8,
    responseRatePct: 80,
    reengagementRatePct: 45,
    saveRatePct: 30,
    behaviourImprovementRatePct: 50,
    membersSavedThisMonth: 2,
    revenueRetainedThisMonthGBP: 110,
    coachRetentionScore: 85,
    outreachStreakDays: 14,
  },
  {
    coachId: "c4",
    membersAssignedCount: 1,
    atRiskAssignedCount: 1,
    contactedTodayCount: 1,
    contactedThisWeekCount: 4,
    contactCoveragePct: 50,
    avgResponseTimeHours: 6.2,
    responseRatePct: 60,
    reengagementRatePct: 28,
    saveRatePct: 15,
    behaviourImprovementRatePct: 35,
    membersSavedThisMonth: 0,
    revenueRetainedThisMonthGBP: 0,
    coachRetentionScore: 58,
    outreachStreakDays: 1,
  },
];

export const MOCK_TEAM_METRICS: TeamMetrics = {
  revenueAtRiskGBP: 1845,
  membersAtRiskCount: 7,
  membersSavedThisMonth: 5,
  revenueRetainedThisMonthGBP: 305,
  retentionRatePct: 87,
};

export const MOCK_AUTOMATION_RULES: AutomationRule[] = [
  { id: "r1", name: "Auto-assign by last session coach", enabled: true, description: "Assign at-risk members to the coach who ran their last session" },
  { id: "r2", name: "Auto-task on risk threshold", enabled: true, description: "Create task when member crosses risk threshold" },
  { id: "r3", name: "Auto-follow-up if no response", enabled: true, description: "Create follow-up task if no response after 3 days" },
  { id: "r4", name: "Escalate to manager", enabled: true, description: "Escalate if no action after 5 days" },
];
